name: CowBox

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  tests:
    name: Tests
    runs-on: macos-15
    steps:
      - name: Run checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          curl -s https://raw.githubusercontent.com/Swift-CowBox/Swift-CowBox/refs/heads/main/test.sh | sh
